name: Test Directory
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Test Directory Structure
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.1f1-webgl-1.0
    env:
      DOTNET_ROOT: '/opt/unity/Editor/Data/NetCore'
    steps:
      - name: Print Data directory
        run: ls '/opt/unity/Editor/Data'
      - name: Print Data recursive
        run: ls -R '/opt/unity/Editor/Data'
