name: Build and Test

on:
  pull_request:
    branches:
      - main
      - Develop

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:   
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    # available list of containers here:
    # https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated&name=ubuntu-2020.1.17f1-base
    container: unityci/editor:ubuntu-2021.3.2f1-webgl-1.0.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Update
        run: apt update
        
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install DotNet SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
          
      - name: Install Sonar Scanner
        run: dotnet tool install --global dotnet-sonarscanner --version 5.5.3

      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          find .. -type f -name "*.sln"
          /github/home/.dotnet/tools/dotnet-sonarscanner begin \
            /o:leonardotpereira \
            /k:LeonardoTPereira_GGJ2022 \
            /n:GGJ2022 \
            /d:sonar.verbose=false \
            /d:sonar.login=$SONAR_TOKEN \
            /d:sonar.host.url=https://sonarcloud.io \
            /d:sonar.cpd.exclusions=Assets/Tests/** \
            /d:sonar.coverage.exclusions=Assets/Tests/** \
            /d:sonar.exclusions=Packages/** \
            ${{ steps.semantic.outputs.new_release_published == 'true' && format('/v:{0}',steps.semantic.outputs.new_release_version) || '' }} \
            /d:sonar.cs.nunit.reportsPaths=Tests/editmode-results.xml,Tests/playmode-results.xml \
            /d:sonar.cs.opencover.reportsPaths=Tests/GGJ2022-opencov/EditMode/TestCoverageResults_0000.xml,Tests/GGJ2022-opencov/PlayMode/TestCoverageResults_0000.xml
          dotnet build GGJ2022.sln
          /github/home/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login=$SONAR_TOKEN

  buildWebGL:
    needs: sonarcloud
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.2f1-webgl-1.0.1
    strategy:
        fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-2020.3.16
          restore-keys: |
            Library-build-
            Library-

      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL

      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL
