name: Build and Test

on:
  pull_request:
    branches:
      - main
      - Develop

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:   
  buildWebGL:
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.2f1-webgl-1.0.1

    steps:
      - name: Activate unity
      # exit code is 1 for manual activation
        continue-on-error: true
        run: |          
          echo "$UNITY_LICENSE" | tr -d '\r' > UnityLicenseFile.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile UnityLicenseFile.ulf -quit | echo "Activation finished"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build WebGL
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
      
      - name: Updloads Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL
